### PR TITLE
fix(catalog): Typo on buttons configurator

### LINKED ISSUE #704: [Bug] Demo app - button configurator - rename iconSize
Bug : On android demo app, for `Button` configurator, `iconSize` label is wrong, it should be replaced by `buttonSize`

buttonConfiguratorBug

### PR DESCRIPTION
**Pull request by soulcramer**
## 📋 Changes description

Change the label and add missing intents

## 📸 Screenshots

/

<table>
<tr>
 <td> Before
 <td> After
<tr>
 <td>
 <td>
</table>

## 🗒️ Other info

Close #704

### CODE REVIEW

File: catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt [hunk 1]
```diff
@@ -85,7 +87,7 @@ private fun IconButtonSample() {
         var intent by remember { mutableStateOf(IconButtonIntent.Main) }
         var contentDescription by remember { mutableStateOf("Content Description") }
 
-        ConfigedIconButton(
+        ConfiggedIconButton(
```
Comment (SimonMarquis) [inline catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt:90]: nit: `ConfiguredIconButton` would be more appropriate tbh 🙈

**Review by SimonMarquis — DISMISSED** [review]

File: catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt (hunk 1 above)
Comment (soulcramer) [reply catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt:90]: It's because it's a confit 🥴🙈
_will change it_

**Review by kazaky — APPROVED** [review]
LGTM
