### PR TITLE
fix: Fix the button end icon being squished when content is too long

### LINKED ISSUE #916: [Bug]: Button Icon End doesn't show on Buttons if it's a multi line button
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

A bug happened!
Screenshot 2024-01-24 at 11 20 51 AM

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by soulcramer**
## 📋 Changes

We use the weight modifier to force the content to take only the space it has available instead of pushing the other contents

## 🤔 Context

Closes #916  

## ✅ Checklist

- [x] I have reviewed the submitted code.
- [x] I have tested on a phone device/emulator.

## 📸 Screenshots

<table>
  <tr>
    <th>Old</th>
    <th>New</th>
  </tr>
  <tr>
    <td>image</td>
    <td>image
</td>
  </tr>
</table>

### CODE REVIEW

File: spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt [hunk 1]
```diff
@@ -117,7 +117,10 @@ internal fun BaseSparkButton(
             Spacer(Modifier.width(SparkButtonDefaults.IconSpacing))
         }
         ProvideTextStyle(value = SparkTheme.typography.callout) {
-            content()
+            Row(
+                modifier = Modifier.weight(1f, false),
```
Comment (SimonMarquis) [inline spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt:121]: nit: can we add an explicit parameter name here?

Comment (soulcramer) [reply spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt:121]: Sure!

**Review by SimonMarquis — APPROVED** [review]
