### PR TITLE
fix: ModalFullScreenScaffold has now a spacing between button in portrait and add reverse order

### LINKED ISSUE #546: [Bug][ModalFullScreenScaffold]: Buttons layout & position
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

While testing the Composable **ModalFullScreenScaffold** on the version 0.3.0 of Spark, I encountered some issues: 

- If you rotate your screen on a smartphone from a portait to landscape mode, the buttons of the modals disappeared or at least are not visible on the screen
- On a small tablet, it seems that the primaryButton is not visible
- I think we should have a padding between the main primary button and the secondary button, that's not the case

You can make a reproducible example, using the code below:

```
LighthouseTheme {
    ModalFullScreenScaffold(
        onClose = { dismiss() },
        primaryButton = {
            ButtonFilled(
                onClick = { dismiss() },
                text = "Primary Action",
                intent = ButtonIntent.Primary,
                modifier = Modifier.fillMaxWidth(),
            )
        },
        secondaryButton = {
            ButtonOutlined(
                onClick = { dismiss() },
                text = "Secondary Acton",
                intent = ButtonIntent.Secondary,
                modifier = Modifier.fillMaxWidth(),
            )
        }
    ) {
        // My scrollable composable
    }
}
```

And find below some screenshots, which have been tested on the following emulators:

- Pixel 4A - Android 11 (API 30)
- Nexus 7 - Android 10 (API 29)  

Screenshot 2023-07-24 at 15 16 29

Screenshot_20230724_115659

https://github.com/adevinta/spark-android/assets/4136370/e4a89e61-47c0-4adc-81c8-6dc398d34ed5

Screenshot 2023-07-24 at 12 24 26

Screenshot 2023-07-24 at 12 24 34

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by soulcramer**
## 📋 Changes description

Add spacing to buttons and add a new `reverseButtonOrder` param to, like its name indiquate, reverse the order between the support and main button.

## 🤔 Context

As mentioned [here](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1689755220968659) a spacing was missing between buttons in portrait mode

## 📸 Screenshots

<table>
<tr>
 <td> Before 
 <td> After
<tr>
 <td> 
 <td> 
</table>

## 🗒️ Other info

Close #546

### CODE REVIEW

**Review by MarinaRomanova — DISMISSED** [review]

File: spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt [hunk 1]
```diff
@@ -78,6 +78,7 @@ import com.adevinta.spark.tools.preview.DevicePreviews
  * @param illustration whether the modal display a close icon, and its corresponding action
  * @param mainButton the main actions for this modal (should be a [ButtonFilled])
  * @param supportButton the support or alternative actions for this modal (should any other button than [ButtonFilled])
+ * @param reverseButtonOrder inverse the order of the buttons, so the mainButton button is shown at the top in portrait mode
```
Comment (SimonMarquis) [inline spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt:81]: nit: add square brackets around parameter names to make them clickable :)
```suggestion
 * @param reverseButtonOrder inverse the order of the buttons, so the [mainButton] button is shown at the top in portrait mode
```

**Review by SimonMarquis — APPROVED** [review]
